services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dudecourse}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dudecourse}
      POSTGRES_USER: ${POSTGRES_USER:-dudecourse}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '127.0.0.1:${POSTGRES_PORT:-5432}:5432'
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
